/* orbitsa.c -- simulated annealing for a large induced forest F of Q_d that is a union of orbits of a
   group G of automorphisms of Q_d (G generated by maps x -> pi(x) XOR t given on the command line;
   no generators = trivial group = unrestricted search).
   Move: pick a random orbit not in F, add it; then repeatedly scan the edges of Q_d[F] with union-find and,
   whenever an edge closes a cycle, evict the orbit of one of its endpoints that is not the added orbit
   (random choice); if both endpoints lie in the added orbit the move is rejected. Metropolis on |F|.
   The best F is re-checked to be a forest and written as a 0/1 indicator line (char v = '1' iff v in F).
   Usage: orbitsa d seed iters T0 T1 outfile [gen ...]   gen = "p0,p1,...,p_{d-1}:t" (bit j -> bit p_j, then XOR t) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
static int d, n;
static unsigned long long rs;
static inline unsigned long long rnd(void){ rs^=rs<<13; rs^=rs>>7; rs^=rs<<17; return rs; }
static inline double urand(void){ return (rnd()>>11)*(1.0/9007199254740992.0); }
static int par[1<<12];
static int fp(int x){ while(par[x]!=x){ par[x]=par[par[x]]; x=par[x]; } return x; }
static int orb[1<<12], norb, osz[1<<12], ostart[1<<12], overt[1<<12];
static char inF[1<<12], oin[1<<12];
static int gpi[32][16], gt[32], ng;
static int apply(int g,int x){ int y=0; for(int j=0;j<d;j++) if((x>>j)&1) y|=1<<gpi[g][j]; return y^gt[g]; }
static int is_forest(const char*F){ for(int v=0;v<n;v++) par[v]=v;
  for(int v=0;v<n;v++) if(F[v]) for(int j=0;j<d;j++){ int w=v^(1<<j); if(w>v&&F[w]){ int a=fp(v),b=fp(w); if(a==b) return 0; par[a]=b; } } return 1; }
static int setorb(int o,int val){ for(int i=0;i<osz[o];i++) inF[overt[ostart[o]+i]]=val; oin[o]=val; return osz[o]; }
int main(int argc,char**argv){
  d=atoi(argv[1]); n=1<<d; rs=0x9E3779B97F4A7C15ULL^((unsigned long long)atoll(argv[2])*0x2545F4914F6CDD1DULL); if(!rs) rs=1;
  long long iters=atoll(argv[3]); double T0=atof(argv[4]),T1=atof(argv[5]);
  ng=0; for(int a=7;a<argc;a++){ char*s=argv[a]; for(int j=0;j<d;j++){ gpi[ng][j]=strtol(s,&s,10); if(*s==','||*s==':') s++; } gt[ng]=(*s)?atoi(s):0; ng++; }
  for(int v=0;v<n;v++) orb[v]=-1; norb=0; int pos=0;
  for(int v=0;v<n;v++) if(orb[v]<0){ int o=norb++; ostart[o]=pos; osz[o]=0; orb[v]=o; overt[pos++]=v; osz[o]++;
    for(int k=ostart[o];k<pos;k++){ int x=overt[k]; for(int g=0;g<ng;g++){ int y=apply(g,x); if(orb[y]<0){ orb[y]=o; overt[pos++]=y; osz[o]++; } } } }
  fprintf(stderr,"orbits %d\n",norb);
  memset(inF,0,n); memset(oin,0,norb);
  int size=0,best=0; static char bestF[1<<12];
  static int evl[1<<12]; static char saveF[1<<12], saveo[1<<12];
  for(long long it=0; it<iters; it++){
    double T=T0*pow(T1/T0,(double)it/iters);
    int o=rnd()%norb; if(oin[o]) continue;
    memcpy(saveF,inF,n); memcpy(saveo,oin,norb);
    int delta=setorb(o,1), ok=1;
    for(int rounds=0; rounds<64 && ok; rounds++){
      for(int v=0;v<n;v++) par[v]=v;
      int clean=1;
      /* scan edges in random rotation to vary which edge is found first */
      int off=rnd()%n;
      for(int t=0;t<n && ok;t++){ int v=(t+off)&(n-1); if(!inF[v]) continue;
        for(int j=0;j<d;j++){ int w=v^(1<<j); if(w>v && inF[w]){ int a=fp(v),b=fp(w);
          if(a==b){ clean=0; int ov=orb[v], ow=orb[w]; int e;
            if(ov==o && ow==o){ ok=0; break; }
            else if(ov==o) e=ow; else if(ow==o) e=ov; else e=(rnd()&1)?ov:ow;
            delta-=setorb(e,0); goto rescan; }
          par[a]=b; } } }
      if(clean) break;
      rescan: ;
    }
    if(ok && !is_forest(inF)) ok=0;
    if(ok && (delta>=0 || urand()<exp(delta/T))){ size+=delta; if(size>best){ best=size; memcpy(bestF,inF,n);
        fprintf(stderr,"it %lld |F|=%d |S|=%d\n",it,best,n-best); } }
    else { memcpy(inF,saveF,n); memcpy(oin,saveo,norb); }
  }
  if(!is_forest(bestF)){ printf("ERROR\n"); return 1; }
  FILE*fo=fopen(argv[6],"w"); for(int v=0;v<n;v++) fputc('0'+bestF[v],fo); fputc('\n',fo); fclose(fo);
  printf("d=%d orbits=%d best |F|=%d |S|=%d\n",d,norb,best,n-best);
  return 0;
}
